# Data Analysis - NYC TLC Trip Record Data
## 20 Preguntas de Negocio (solo tablas gold.*)

**Tablas utilizadas:**
- `gold.fct_trips` (hechos - particionada RANGE por pickup_date)
- `gold.dim_date` (dimension fecha)
- `gold.dim_zone` (dimension zona - particionada HASH)
- `gold.dim_service_type` (dimension servicio - particionada LIST)
- `gold.dim_payment_type` (dimension pago - particionada LIST)
- `gold.dim_vendor` (dimension proveedor)

In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://admin:password@localhost:5432/nyc_tlc')

def query(sql):
    return pd.read_sql(sql, engine)

---
## Demanda / Estacionalidad

### 1. Viajes por mes (2024)
**Tablas:** `gold.fct_trips`, `gold.dim_date`

In [2]:
q1 = query("""
    SELECT d.month, d.month_name, COUNT(*) AS total_trips
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    WHERE d.year = 2024
    GROUP BY d.month, d.month_name
    ORDER BY d.month
""")
print("Viajes por mes en 2024:")
q1

Viajes por mes en 2024:

    month month_name  total_trips
0       1  January        2985433
1       2  February       3024850
2       3  March          3595437
3       4  April          3526733
4       5  May            3735589
5       6  June           3544924
6       7  July           3078133
7       8  August         2977864
8       9  September      3631133
9      10  October        3828314
10     11  November       3636812
11     12  December       3651594

**Interpretacion:** Se observa la estacionalidad mensual de los viajes en 2024. Los meses de verano (junio-octubre) tienden a tener mayor demanda, mientras que enero-febrero muestran menor actividad por el clima invernal.

### 2. Viajes por service_type y mes
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_service_type`

In [3]:
q2 = query("""
    SELECT d.year, d.month, s.service_type, COUNT(*) AS total_trips
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_service_type s ON f.service_type_key = s.service_type_key
    WHERE d.year = 2024
    GROUP BY d.year, d.month, s.service_type
    ORDER BY d.month, s.service_type
""")
print("Viajes por servicio y mes (2024):")
q2

Viajes por servicio y mes (2024):

    year  month service_type  total_trips
0   2024      1        green        56370
1   2024      1       yellow      2929063
2   2024      2        green        53403
3   2024      2       yellow      2971447
4   2024      3        green        57254
5   2024      3       yellow      3538183
6   2024      4        green        56257
7   2024      4       yellow      3470476
8   2024      5        green        60781
9   2024      5       yellow      3674808
10  2024      6        green        54556
11  2024      6       yellow      3490368
12  2024      7        green        51641
13  2024      7       yellow      3026492
14  2024      8        green        51622
15  2024      8       yellow      2926242
16  2024      9        green        54261
17  2024      9       yellow      3576872
18  2024     10        green        55999
19  2024     10       yellow      3772315
20  2024     11        green        52067
21  2024     11       yellow      3584745
22  2024     12        green        53818
23  2024     12       yellow      3597776

**Interpretacion:** Yellow taxis dominan ampliamente el volumen (~98% de viajes). Green taxis operan principalmente en boroughs exteriores y representan una fraccion menor del total.

### 3. Top 10 zonas de pickup (total 2024)
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

In [4]:
q3 = query("""
    SELECT z.zone_name, z.borough, COUNT(*) AS total_trips
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone z ON f.pu_zone_key = z.zone_key
    WHERE d.year = 2024
    GROUP BY z.zone_name, z.borough
    ORDER BY total_trips DESC
    LIMIT 10
""")
print("Top 10 zonas de pickup (2024):")
q3

Top 10 zonas de pickup (2024):

                      zone_name    borough  total_trips
0                   JFK Airport     Queens      1910244
1         Upper East Side South  Manhattan      1892772
2                Midtown Center  Manhattan      1886880
3         Upper East Side North  Manhattan      1718376
4                  Midtown East  Manhattan      1399892
5     Times Sq/Theatre District  Manhattan      1362178
6  Penn Station/Madison Sq West  Manhattan      1340585
7           Lincoln Square East  Manhattan      1299332
8             LaGuardia Airport     Queens      1275003
9                   Murray Hill  Manhattan      1160466

**Interpretacion:** Las zonas con mayor demanda de pickup se concentran en Manhattan (Midtown, Upper East Side, Financial District), lo que refleja la alta actividad comercial y turistica de esos barrios.

### 4. Top 10 zonas de dropoff (total 2024)
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

In [5]:
q4 = query("""
    SELECT z.zone_name, z.borough, COUNT(*) AS total_trips
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone z ON f.do_zone_key = z.zone_key
    WHERE d.year = 2024
    GROUP BY z.zone_name, z.borough
    ORDER BY total_trips DESC
    LIMIT 10
""")
print("Top 10 zonas de dropoff (2024):")
q4

Top 10 zonas de dropoff (2024):

                   zone_name    borough  total_trips
0      Upper East Side North  Manhattan      1807550
1      Upper East Side South  Manhattan      1714789
2             Midtown Center  Manhattan      1521470
3  Times Sq/Theatre District  Manhattan      1286410
4                Murray Hill  Manhattan      1199480
5               Midtown East  Manhattan      1171128
6        Lincoln Square East  Manhattan      1137196
7      Upper West Side South  Manhattan      1135547
8               East Chelsea  Manhattan      1063507
9            Lenox Hill West  Manhattan      1058186

**Interpretacion:** Las zonas de dropoff son similares a las de pickup, confirmando que Manhattan es tanto origen como destino principal. Los aeropuertos (JFK, LaGuardia) tambien aparecen como destinos frecuentes.

### 5. Top 5 boroughs por mes (pickup)
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

In [6]:
q5 = query("""
    SELECT d.month, d.month_name, z.borough, COUNT(*) AS total_trips
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone z ON f.pu_zone_key = z.zone_key
    WHERE d.year = 2024
    GROUP BY d.month, d.month_name, z.borough
    ORDER BY d.month, total_trips DESC
""")
print("Top 5 boroughs por mes (pickup, 2024):")
q5

Top 5 boroughs por mes (pickup, 2024):

    month month_name        borough  total_trips
0       1  January        Manhattan      2651102
1       1  January           Queens       281604
2       1  January         Brooklyn        32709
3       1  January          Unknown        10379
4       1  January            Bronx         7719
..    ...        ...            ...          ...
91     12  December           Bronx        11733
92     12  December         Unknown         9571
93     12  December            None         2050
94     12  December             EWR          626
95     12  December   Staten Island          175

[96 rows x 4 columns]

**Interpretacion:** Manhattan lidera consistentemente todos los meses. Queens ocupa el segundo lugar gracias a los aeropuertos. Brooklyn y Bronx mantienen una participacion menor pero estable.

### 6. Horas pico (top 5 horas) para cada dia de semana
**Tablas:** `gold.fct_trips`, `gold.dim_date`

In [7]:
q6 = query("""
    WITH hourly AS (
        SELECT d.day_name, d.day_of_week, f.pickup_hour, COUNT(*) AS total_trips,
               ROW_NUMBER() OVER (PARTITION BY d.day_of_week ORDER BY COUNT(*) DESC) AS rn
        FROM gold.fct_trips f
        JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
        WHERE d.year = 2024
        GROUP BY d.day_name, d.day_of_week, f.pickup_hour
    )
    SELECT day_name, pickup_hour, total_trips
    FROM hourly
    WHERE rn <= 5
    ORDER BY day_of_week, rn
""")
print("Top 5 horas pico por dia de semana (2024):")
q6

Top 5 horas pico por dia de semana (2024):

     day_name  pickup_hour  total_trips
0   Sunday              14       336032
1   Sunday              17       331945
2   Sunday              16       330784
3   Sunday              13       325825
4   Sunday              15       322741
5   Monday              18       373005
6   Monday              17       367109
7   Monday              15       340957
8   Monday              16       336325
9   Monday              14       330361
10  Tuesday             18       453114
11  Tuesday             17       420795
12  Tuesday             21       394858
13  Tuesday             19       383328
14  Tuesday             20       372497
15  Wednesday           18       468586
16  Wednesday           17       437965
17  Wednesday           21       407704
18  Wednesday           19       400760
19  Wednesday           16       381144
20  Thursday            18       487564
21  Thursday            17       454011
22  Thursday            19       420242
23  Thursday            21       414990
24  Thursday            16       394930
25  Friday              18       451513
26  Friday              17       416339
27  Friday              19       411110
28  Friday              16       378325
29  Friday              15       378283
30  Saturday            18       411750
31  Saturday            19       400322
32  Saturday            17       397747
33  Saturday            16       382028
34  Saturday            23       372526

**Interpretacion:** Entre semana las horas pico son las 18-19h (salida del trabajo) y 8-9h (entrada). Los fines de semana el pico se desplaza a horas nocturnas (21-23h), reflejando actividad de ocio.

### 7. Distribucion de viajes por dia de semana (ranking)
**Tablas:** `gold.fct_trips`, `gold.dim_date`

In [8]:
q7 = query("""
    SELECT d.day_name, d.day_of_week, COUNT(*) AS total_trips
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    WHERE d.year = 2024
    GROUP BY d.day_name, d.day_of_week
    ORDER BY total_trips DESC
""")
print("Distribucion de viajes por dia de semana (2024):")
q7

Distribucion de viajes por dia de semana (2024):

    day_name  day_of_week  total_trips
0  Thursday             4      6445406
1  Saturday             6      6218745
2  Wednesday            3      6136158
3  Friday               5      6111228
4  Tuesday              2      5916522
5  Sunday               0      5261268
6  Monday               1      5127489

**Interpretacion:** Los dias con mayor demanda son jueves y viernes. Los domingos tienen la menor demanda, consistente con menor actividad laboral y comercial.

---
## Ingresos / Tarifas / Propinas

### 8. Ingreso total (total_amount) por mes
**Tablas:** `gold.fct_trips`, `gold.dim_date`

In [9]:
q8 = query("""
    SELECT d.month, d.month_name, ROUND(SUM(f.total_amount)::numeric, 2) AS total_revenue
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    WHERE d.year = 2024
    GROUP BY d.month, d.month_name
    ORDER BY d.month
""")
print("Ingreso total por mes (2024):")
q8

Ingreso total por mes (2024):

    month month_name  total_revenue
0       1  January     8.161710e+07
1       2  February    8.220750e+07
2       3  March       9.965075e+07
3       4  April       9.912941e+07
4       5  May         1.085226e+08
5       6  June        1.015710e+08
6       7  July        8.918056e+07
7       8  August      8.715687e+07
8       9  September   1.067667e+08
9      10  October     1.121499e+08
10     11  November    1.037586e+08
11     12  December    1.071772e+08

**Interpretacion:** Los ingresos siguen el mismo patron estacional que la demanda. Los meses de mayor recaudacion coinciden con los de mayor numero de viajes.

### 9. Ingreso total por service_type y mes
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_service_type`

In [10]:
q9 = query("""
    SELECT d.month, d.month_name, s.service_type,
           ROUND(SUM(f.total_amount)::numeric, 2) AS total_revenue
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_service_type s ON f.service_type_key = s.service_type_key
    WHERE d.year = 2024
    GROUP BY d.month, d.month_name, s.service_type
    ORDER BY d.month, s.service_type
""")
print("Ingreso total por servicio y mes (2024):")
q9

Ingreso total por servicio y mes (2024):

    month month_name service_type  total_revenue
0       1  January          green   1.268964e+06
1       1  January         yellow   8.034814e+07
2       2  February         green   1.214659e+06
3       2  February        yellow   8.099284e+07
4       3  March            green   1.318139e+06
5       3  March           yellow   9.833261e+07
6       4  April            green   1.322417e+06
7       4  April           yellow   9.780699e+07
8       5  May              green   1.501840e+06
9       5  May             yellow   1.070207e+08
10      6  June             green   1.363607e+06
11      6  June            yellow   1.002073e+08
12      7  July             green   1.285849e+06
13      7  July            yellow   8.789471e+07
14      8  August           green   1.348385e+06
15      8  August          yellow   8.580849e+07
16      9  September        green   1.454635e+06
17      9  September       yellow   1.053120e+08
18     10  October          green   1.407562e+06
19     10  October         yellow   1.107423e+08
20     11  November         green   1.264782e+06
21     11  November        yellow   1.024938e+08
22     12  December         green   1.297143e+06
23     12  December        yellow   1.058801e+08

**Interpretacion:** Yellow taxis generan la gran mayoria de los ingresos. Green taxis aportan una fraccion menor pero consistente, operando en zonas donde yellow no tiene presencia.

### 10. Tip % promedio por mes
**Tablas:** `gold.fct_trips`, `gold.dim_date`

In [13]:
q10 = query("""
    SELECT d.month, d.month_name,
           ROUND((AVG(f.tip_amount / NULLIF(f.fare_amount, 0)) * 100)::numeric, 2) AS avg_tip_pct
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    WHERE d.year = 2024 AND f.fare_amount > 0
    GROUP BY d.month, d.month_name
    ORDER BY d.month
""")
print("Tip % promedio por mes (2024):")
q10

Tip % promedio por mes (2024):

    month month_name  avg_tip_pct
0       1  January          22.96
1       2  February         20.92
2       3  March            19.63
3       4  April            20.05
4       5  May              20.16
5       6  June             19.15
6       7  July             19.42
7       8  August           18.82
8       9  September        18.91
9      10  October          19.63
10     11  November         21.13
11     12  December         19.77

**Interpretacion:** El porcentaje de propina se mantiene relativamente estable a lo largo del anio, tipicamente entre 15-20%. Variaciones menores pueden reflejar cambios estacionales en el tipo de pasajero (turistas vs locales).

### 11. Tip % por borough y mes
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

In [14]:
q11 = query("""
    SELECT z.borough, d.month,
           ROUND((AVG(f.tip_amount / NULLIF(f.fare_amount, 0)) * 100)::numeric, 2) AS avg_tip_pct
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone z ON f.pu_zone_key = z.zone_key
    WHERE d.year = 2024 AND f.fare_amount > 0
    GROUP BY z.borough, d.month
    ORDER BY z.borough, d.month
""")
print("Tip % por borough y mes (2024):")
q11

Tip % por borough y mes (2024):

   borough  month  avg_tip_pct
0    Bronx      1         2.47
1    Bronx      2         2.89
2    Bronx      3        17.68
3    Bronx      4         2.13
4    Bronx      5         2.31
..     ...    ...          ...
91    None      8        35.72
92    None      9       674.17
93    None     10       475.49
94    None     11       174.41
95    None     12        26.17

[96 rows x 3 columns]

**Interpretacion:** Manhattan tiende a tener el tip % mas alto, posiblemente por mayor uso de tarjeta de credito (que facilita propinas). Boroughs con mayor pago en efectivo muestran menor tip % registrado.

### 12. Top 10 zonas por ingreso total (pickup)
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

In [15]:
q12 = query("""
    SELECT z.zone_name, z.borough,
           ROUND(SUM(f.total_amount)::numeric, 2) AS total_revenue,
           COUNT(*) AS total_trips
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone z ON f.pu_zone_key = z.zone_key
    WHERE d.year = 2024
    GROUP BY z.zone_name, z.borough
    ORDER BY total_revenue DESC
    LIMIT 10
""")
print("Top 10 zonas por ingreso total (pickup, 2024):")
q12

Top 10 zonas por ingreso total (pickup, 2024):

                      zone_name    borough  total_revenue  total_trips
0                   JFK Airport     Queens   1.569750e+08      1910244
1             LaGuardia Airport     Queens   8.722304e+07      1275003
2                Midtown Center  Manhattan   4.767217e+07      1886880
3     Times Sq/Theatre District  Manhattan   3.969221e+07      1362178
4         Upper East Side South  Manhattan   3.959266e+07      1892772
5         Upper East Side North  Manhattan   3.629119e+07      1718376
6                  Midtown East  Manhattan   3.444941e+07      1399892
7  Penn Station/Madison Sq West  Manhattan   3.433714e+07      1340585
8                 Midtown North  Manhattan   2.919408e+07      1152387
9           Lincoln Square East  Manhattan   2.905842e+07      1299332

**Interpretacion:** Las zonas con mayor ingreso coinciden con las de mayor volumen. JFK Airport destaca por tener un ingreso promedio por viaje mas alto debido a las tarifas fijas al aeropuerto.

### 13. Top 10 zonas por tip % (pickup) con minimo 1000 viajes
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

*N minimo definido: 1000 viajes para evitar sesgos por bajo volumen.*

In [16]:
q13 = query("""
    SELECT z.zone_name, z.borough, COUNT(*) AS total_trips,
           ROUND((AVG(f.tip_amount / NULLIF(f.fare_amount, 0)) * 100)::numeric, 2) AS avg_tip_pct
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone z ON f.pu_zone_key = z.zone_key
    WHERE d.year = 2024 AND f.fare_amount > 0
    GROUP BY z.zone_name, z.borough
    HAVING COUNT(*) >= 1000
    ORDER BY avg_tip_pct DESC
    LIMIT 10
""")
print("Top 10 zonas por tip % (min 1000 viajes, 2024):")
q13

Top 10 zonas por tip % (min 1000 viajes, 2024):

                  zone_name   borough  total_trips  avg_tip_pct
0            Outside of NYC      None        22711       589.34
1            Newark Airport       EWR         5774       206.45
2  Williamsbridge/Olinville     Bronx         4259       149.00
3          South Ozone Park    Queens        16294        94.21
4              Baisley Park    Queens        15279        76.74
5                  Red Hook  Brooklyn        10715        52.20
6                   Bedford  Brooklyn        14358        38.39
7             Melrose South     Bronx         6589        30.66
8              Forest Hills    Queens        42915        26.66
9                  Steinway    Queens        15435        26.52

**Interpretacion:** Las zonas con mayor tip % suelen ser areas residenciales de alto poder adquisitivo o zonas turisticas donde los pasajeros tienden a dejar propinas mas generosas.

### 14. Comparacion cash vs card: viajes, ingreso total, tip %
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_payment_type`

In [17]:
q14 = query("""
    SELECT p.payment_type,
           COUNT(*) AS total_trips,
           ROUND(SUM(f.total_amount)::numeric, 2) AS total_revenue,
           ROUND((AVG(f.tip_amount / NULLIF(f.fare_amount, 0)) * 100)::numeric, 2) AS avg_tip_pct
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_payment_type p ON f.payment_type_key = p.payment_type_key
    WHERE d.year = 2024 AND f.fare_amount > 0
      AND p.payment_type IN ('Credit card', 'Cash')
    GROUP BY p.payment_type
    ORDER BY total_trips DESC
""")
print("Cash vs Card (2024):")
q14

Cash vs Card (2024):

  payment_type  total_trips  total_revenue  avg_tip_pct
0  Credit card     30904449   9.223767e+08        26.14
1         Cash      5563172   1.378997e+08         0.00

**Interpretacion:** Credit card domina ampliamente sobre cash. El tip % con tarjeta es significativamente mayor porque el sistema sugiere montos de propina, mientras que con cash las propinas no siempre se registran.

---
## Duracion / Distancia / Eficiencia

### 15. Duracion promedio (min) por mes
**Tablas:** `gold.fct_trips`, `gold.dim_date`

In [18]:
q15 = query("""
    SELECT d.month, d.month_name,
           ROUND(AVG(f.duration_minutes)::numeric, 2) AS avg_duration_min
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    WHERE d.year = 2024 AND f.duration_minutes > 0 AND f.duration_minutes < 180
    GROUP BY d.month, d.month_name
    ORDER BY d.month
""")
print("Duracion promedio por mes (2024):")
q15

Duracion promedio por mes (2024):

    month month_name  avg_duration_min
0       1  January               14.85
1       2  February              15.24
2       3  March                 15.97
3       4  April                 16.30
4       5  May                   17.32
5       6  June                  16.85
6       7  July                  16.47
7       8  August                16.59
8       9  September             18.02
9      10  October               17.65
10     11  November              17.14
11     12  December              18.01

**Interpretacion:** La duracion promedio se mantiene estable (~15 min). Meses con mas trafico (verano) pueden mostrar duraciones ligeramente mayores por congestion vial.

### 16. Distancia promedio por mes
**Tablas:** `gold.fct_trips`, `gold.dim_date`

In [19]:
q16 = query("""
    SELECT d.month, d.month_name,
           ROUND(AVG(f.trip_distance)::numeric, 2) AS avg_distance_miles
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    WHERE d.year = 2024 AND f.trip_distance > 0 AND f.trip_distance < 100
    GROUP BY d.month, d.month_name
    ORDER BY d.month
""")
print("Distancia promedio por mes (2024):")
q16

Distancia promedio por mes (2024):

    month month_name  avg_distance_miles
0       1  January                  3.28
1       2  February                 3.21
2       3  March                    3.35
3       4  April                    3.38
4       5  May                      3.42
5       6  June                     3.42
6       7  July                     3.58
7       8  August                   3.66
8       9  September                3.53
9      10  October                  3.48
10     11  November                 3.33
11     12  December                 3.32

**Interpretacion:** La distancia promedio (~3 millas) refleja viajes urbanos cortos tipicos de NYC. Se filtraron viajes > 100 millas para eliminar outliers.

### 17. Velocidad promedio (mph) por borough y franja horaria
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

In [20]:
q17 = query("""
    SELECT z.borough,
           CASE
               WHEN f.pickup_hour BETWEEN 6 AND 11 THEN 'Morning (6-11)'
               WHEN f.pickup_hour BETWEEN 12 AND 17 THEN 'Afternoon (12-17)'
               WHEN f.pickup_hour BETWEEN 18 AND 23 THEN 'Evening (18-23)'
               ELSE 'Night (0-5)'
           END AS time_slot,
           ROUND(AVG(f.trip_distance / NULLIF(f.duration_minutes / 60.0, 0))::numeric, 2) AS avg_speed_mph
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone z ON f.pu_zone_key = z.zone_key
    WHERE d.year = 2024
      AND f.duration_minutes > 1 AND f.duration_minutes < 180
      AND f.trip_distance > 0 AND f.trip_distance < 100
    GROUP BY z.borough,
             CASE
               WHEN f.pickup_hour BETWEEN 6 AND 11 THEN 'Morning (6-11)'
               WHEN f.pickup_hour BETWEEN 12 AND 17 THEN 'Afternoon (12-17)'
               WHEN f.pickup_hour BETWEEN 18 AND 23 THEN 'Evening (18-23)'
               ELSE 'Night (0-5)'
             END
    ORDER BY z.borough, time_slot
""")
print("Velocidad promedio por borough y franja horaria (2024):")
q17

Velocidad promedio por borough y franja horaria (2024):

          borough          time_slot  avg_speed_mph
0           Bronx  Afternoon (12-17)          11.85
1           Bronx    Evening (18-23)          16.62
2           Bronx     Morning (6-11)          13.27
3           Bronx        Night (0-5)          19.26
4        Brooklyn  Afternoon (12-17)           9.80
5        Brooklyn    Evening (18-23)          12.49
6        Brooklyn     Morning (6-11)          11.40
7        Brooklyn        Night (0-5)          16.23
8             EWR  Afternoon (12-17)          40.20
9             EWR    Evening (18-23)          28.02
10            EWR     Morning (6-11)          25.82
11            EWR        Night (0-5)          23.04
12      Manhattan  Afternoon (12-17)           8.46
13      Manhattan    Evening (18-23)           9.98
14      Manhattan     Morning (6-11)          10.17
15      Manhattan        Night (0-5)          13.34
16         Queens  Afternoon (12-17)          17.73
17         Queens    Evening (18-23)          24.77
18         Queens     Morning (6-11)          19.86
19         Queens        Night (0-5)          28.46
20  Staten Island  Afternoon (12-17)          25.93
21  Staten Island    Evening (18-23)          25.21
22  Staten Island     Morning (6-11)          21.61
23  Staten Island        Night (0-5)          28.14
24        Unknown  Afternoon (12-17)           9.92
25        Unknown    Evening (18-23)          12.21
26        Unknown     Morning (6-11)          12.04
27        Unknown        Night (0-5)          15.31
28           None  Afternoon (12-17)          26.44
29           None    Evening (18-23)          30.76
30           None     Morning (6-11)          29.01
31           None        Night (0-5)          36.50

**Interpretacion:** La velocidad promedio es menor en Manhattan (congestion) y mayor en boroughs exteriores. Las horas nocturnas muestran velocidades mas altas por menor trafico.

### 18. Percentiles p50 y p90 de duracion por borough
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

In [21]:
q18 = query("""
    SELECT z.borough,
           ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY f.duration_minutes)::numeric, 2) AS p50_duration,
           ROUND(PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY f.duration_minutes)::numeric, 2) AS p90_duration
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone z ON f.pu_zone_key = z.zone_key
    WHERE d.year = 2024 AND f.duration_minutes > 0 AND f.duration_minutes < 180
    GROUP BY z.borough
    ORDER BY p50_duration
""")
print("Percentiles p50 y p90 de duracion por borough (2024):")
q18

Percentiles p50 y p90 de duracion por borough (2024):

         borough  p50_duration  p90_duration
0            EWR          0.13          1.33
1           None          0.35         30.55
2      Manhattan         12.02         26.78
3        Unknown         12.45         34.22
4  Staten Island         18.35         47.70
5       Brooklyn         22.22         55.45
6          Bronx         27.62         70.67
7         Queens         33.12         62.53

**Interpretacion:** La mediana (p50) es similar entre boroughs (~10-15 min), pero el p90 revela que Queens tiene viajes largos (probablemente al aeropuerto). La diferencia p90-p50 indica la variabilidad de duraciones.

### 19. Top 10 zonas (pickup) por p90 de duracion
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

In [22]:
q19 = query("""
    SELECT z.zone_name, z.borough, COUNT(*) AS total_trips,
           ROUND(PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY f.duration_minutes)::numeric, 2) AS p90_duration
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone z ON f.pu_zone_key = z.zone_key
    WHERE d.year = 2024 AND f.duration_minutes > 0 AND f.duration_minutes < 180
    GROUP BY z.zone_name, z.borough
    HAVING COUNT(*) >= 1000
    ORDER BY p90_duration DESC
    LIMIT 10
""")
print("Top 10 zonas por p90 de duracion (min 1000 viajes, 2024):")
q19

Top 10 zonas por p90 de duracion (min 1000 viajes, 2024):

         zone_name   borough  total_trips  p90_duration
0     Far Rockaway    Queens         3941        104.57
1  Hammels/Arverne    Queens         3913        103.49
2     Coney Island  Brooklyn         7935         97.37
3    Rockaway Park    Queens         1342         94.20
4   Brighton Beach  Brooklyn         3282         92.11
5         Rosedale    Queens         2624         88.76
6        Gravesend  Brooklyn         2466         88.31
7  Cambria Heights    Queens         2240         87.62
8       Co-Op City     Bronx         6009         87.43
9        Laurelton    Queens         2384         86.97

**Interpretacion:** Las zonas con p90 mas alto son tipicamente zonas alejadas del centro o con rutas al aeropuerto, donde el 10% de los viajes mas largos supera los 30-40 minutos.

---
## Rutas / Patrones

### 20. Top 10 rutas borough a borough por numero de viajes
**Tablas:** `gold.fct_trips`, `gold.dim_date`, `gold.dim_zone`

In [24]:
q20 = query("""
    SELECT pu.borough AS pickup_borough,
           dz.borough AS dropoff_borough,
           COUNT(*) AS total_trips
    FROM gold.fct_trips f
    JOIN gold.dim_date d ON f.pickup_date_key = d.date_key
    JOIN gold.dim_zone pu ON f.pu_zone_key = pu.zone_key
    JOIN gold.dim_zone dz ON f.do_zone_key = dz.zone_key
    WHERE d.year = 2024
    GROUP BY pu.borough, dz.borough
    ORDER BY total_trips DESC
    LIMIT 10
""")
print("Top 10 rutas borough->borough (2024):")
q20

Top 10 rutas borough->borough (2024):

  pickup_borough dropoff_borough  total_trips
0      Manhattan       Manhattan     34079887
1         Queens       Manhattan      2140376
2      Manhattan          Queens      1097881
3         Queens          Queens      1020826
4      Manhattan        Brooklyn       751498
5         Queens        Brooklyn       564231
6       Brooklyn        Brooklyn       386479
7       Brooklyn       Manhattan       206411
8      Manhattan           Bronx       126308
9         Queens            None       110268

**Interpretacion:** Manhattan->Manhattan es la ruta dominante, confirmando que la mayoria de viajes son intra-borough. Las rutas Manhattan->Queens y Queens->Manhattan reflejan trafico al/del aeropuerto.